name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Normalize lockfile (public registry)
        run: |
          npm install --no-save prettier@latest > /dev/null 2>&1 || true
          node scripts/lock-normalize.mjs || true
          if grep -R "artifactory" package-lock.json; then echo "Found internal host token in lockfile"; exit 1; fi

      - name: Validate resolved URL structure
        run: |
          # Capture any resolved lines pointing at registry.npmjs.org that are missing the '/-/' path segment
          MALFORMED=$(grep '"resolved": "https://registry.npmjs.org/' package-lock.json | grep -v '/-/' || true)
          if [ -n "$MALFORMED" ]; then
            echo "Malformed resolved URL(s) (missing '/-/' segment) detected:";
            echo "$MALFORMED";
            exit 1;
          else
            echo "All resolved URLs include expected '/-/' segment.";
          fi

      - name: Show registry
        run: npm config get registry

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

      # Optional: future bundle analysis (disabled until script added)
      # - name: Build with analysis
      #   run: npm run build:analyze
      # - name: Upload bundle analysis
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: bundle-analysis
      #     path: stats
